project:
  type: website

website:
  title: "Data as Foundation"
  site-url: https://AgileHealthInformatics.github.io/dataasfoundation.github.io
  description: "Building healthcare’s invisible infrastructure"

  navbar:
    left:
      - text: Home
        file: index.qmd
      - text: Book
        menu:
          - text: Overview
            file: book/overview.qmd
          - text: Part I — The Healthcare Data Paradox
            file: book/part1.qmd
          - text: Part II — Fundamentals of Data Management
            file: book/part2.qmd
          - text: Part III — Rethinking Healthcare Data
            file: book/part3.qmd
          - text: Part IV — Building the Infrastructure
            file: book/part4.qmd
          - text: Part V — Enabling the Future of Healthcare
            file: book/part5.qmd
          - text: Part VI — Case Studies & Implementation
            file: book/part6.qmd

  page-footer:
    left: "© Agile Health Informatics Ltd."
    right: "[Contact: tito@agilehealthinformatics.com](mailto:tito@agilehealthinformatics.com)"

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    toc: true
    css: styles.scss
    smooth-scroll: true

execute:
  freeze: auto
